# Generated by Django 4.2.7 on 2023-12-08 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroDeBowling', '0002_remove_estadopista_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopista',
            name='horario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CentroDeBowling.horarios'),
        ),
    ]
