# Generated by Django 4.2.7 on 2023-12-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroDeBowling', '0003_estadopista_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CentroDeBowling.estadoreserva'),
        ),
    ]
