# Generated by Django 4.2.7 on 2023-12-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroDeBowling', '0005_alter_reserva_estado_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='detallesPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentroDeBowling.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='AsignacionPedido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='listapedidos',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='reserva',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
        migrations.DeleteModel(
            name='PrecioProducto',
        ),
        migrations.DeleteModel(
            name='ProductoMenu',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='listapedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='reserva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CentroDeBowling.reserva'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalles',
            field=models.ManyToManyField(to='CentroDeBowling.detallespedido'),
        ),
    ]
